# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: "en"
title: Tao Manh Dung
author: Tao Manh Dung
keywords: "Tao, Manh, Dung, CV, TMD, tamadu"
email: taomanhdung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CV - Tao Manh Dung
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://taomanhdung.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  taomanhdung

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 100
start-delay: 200
delete-delay: 10000
lines: # You can add HTML Tags in the Text
  - text: "<div class='typed-hello'>Hello, I'm Tao</div>SOFTWARE DEVELOPER - TENNIS LOVER"
  #- text: "SOFTWARE DEVELOPER - TENNIS LOVER"

me-img: "/img/my_avatar.jpg"
favicon: "/img/logo.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/manhdung.niit"
  - title: "twitter"
    url: "https://twitter.com/taomanhdung"
  - title: "github"
    url: "https://github.com//taomanhdung"


# Sections shown in the index page
pages_list:
  About me: 'aboutme'
  Projects: 'projects'
  Contact: 'contact'

sass:
    style: compressed

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
port: 8888


